feat: add VolcMiner D1
UpstreamData/pyasic pull request #263
Opened 2024-12-30 14:00 UTC by jpcomps

Adds initial support for the Volcminer D1 (https://www.volcminer.com/)

Few issues:

- API is identical to the Hammer D10, including the identifier in the http headers. Due to this, added the VolcMiner D1 as a HammerModel variant. If we want to create a new model will need to determine a way to distinguish the two. 
- Unfortunately like the D10, expected HR is not provided, so sticker_hashrate is used. Generally fine, however there is now two models (15.15 GH and 17 GH).  Expected this to eventually come up, but as long as we are ok with seeing a percent_hashrate over 100%, leaving the base model hashrate should be sufficient 

Going to leave this in Draft for now, if we are ok with the above assumptions we can merge it as initial support.

2024-12-30 21:04 UTC, b-rowan requested changes

2024-12-30 21:04 UTC, b-rowan commented on pyasic/miners/factory.py
> +                    if "Hammer" in res:
Maybe use res.upper() here, and make both the checks strict.  The else case can warn about an unknown miner subtype or something.

2024-12-30 21:11 UTC, jpcomps commented
@b-rowan only thing left is both will use the BlackMiner api class, so volcminer will use a few of the hammer methods

2024-12-31 17:02 UTC, b-rowan approved these changes

2024-12-31 17:02 UTC, merged